export const CATEGORIES = [
  {
    id: '1',
    name: 'Home',
    slug: 'home',
    subcategories: [],
    featured: true,
    order: 1,
    image: '/assets/home/decor1.jpeg',
  },
  {
    id: '2',
    name: 'Dress Material',
    slug: 'dress-material',
    subcategories: [],
    featured: true,
    order: 2,
    image: '/assets/dress-material/dress1.jpeg',
  },
  {
    id: '3',
    name: 'Sarees',
    slug: 'sarees',
    subcategories: [
      { id: '3-1', name: 'Silk Sarees', slug: 'silk-sarees', categoryId: '3', order: 1 },
      { id: '3-2', name: 'Cotton Sarees', slug: 'cotton-sarees', categoryId: '3', order: 2 },
      { id: '3-3', name: 'Chiffon Sarees', slug: 'chiffon-sarees', categoryId: '3', order: 3 },
      { id: '3-4', name: 'Designer Sarees', slug: 'designer-sarees', categoryId: '3', order: 4 },
      { id: '3-5', name: 'Party Wear Sarees', slug: 'party-wear-sarees', categoryId: '3', order: 5 },
      { id: '3-6', name: 'Casual Sarees', slug: 'casual-sarees', categoryId: '3', order: 6 },
    ],
    featured: true,
    order: 3,
    image: '/assets/sarees/saree1.jpeg',
  },
  {
    id: '4',
    name: 'Suit Sets',
    slug: 'suit-sets',
    subcategories: [
      { id: '4-1', name: 'Anarkali Suits', slug: 'anarkali-suits', categoryId: '4', order: 1 },
      { id: '4-2', name: 'Straight Suits', slug: 'straight-suits', categoryId: '4', order: 2 },
      { id: '4-3', name: 'Palazzo Suits', slug: 'palazzo-suits', categoryId: '4', order: 3 },
      { id: '4-4', name: 'Sharara Suits', slug: 'sharara-suits', categoryId: '4', order: 4 },
      { id: '4-5', name: 'Gharara Suits', slug: 'gharara-suits', categoryId: '4', order: 5 },
      { id: '4-6', name: 'Pakistani Suits', slug: 'pakistani-suits', categoryId: '4', order: 6 },
      { id: '4-7', name: 'Party Wear Suits', slug: 'party-wear-suits', categoryId: '4', order: 7 },
      { id: '4-8', name: 'Wedding Suits', slug: 'wedding-suits', categoryId: '4', order: 8 },
      { id: '4-9', name: 'Casual Suits', slug: 'casual-suits', categoryId: '4', order: 9 },
      { id: '4-10', name: 'Cotton Suits', slug: 'cotton-suits', categoryId: '4', order: 10 },
      { id: '4-11', name: 'Silk Suits', slug: 'silk-suits', categoryId: '4', order: 11 },
      { id: '4-12', name: 'Georgette Suits', slug: 'georgette-suits', categoryId: '4', order: 12 },
    ],
    featured: true,
    order: 4,
    image: '/assets/suit/suit1.jpeg',
  },
  {
    id: '5',
    name: 'Fabrics',
    slug: 'fabrics',
    subcategories: [
      { id: '5-1', name: 'Cotton Fabrics', slug: 'cotton-fabrics', categoryId: '5', order: 1 },
      { id: '5-2', name: 'Silk Fabrics', slug: 'silk-fabrics', categoryId: '5', order: 2 },
      { id: '5-3', name: 'Georgette Fabrics', slug: 'georgette-fabrics', categoryId: '5', order: 3 },
      { id: '5-4', name: 'Chiffon Fabrics', slug: 'chiffon-fabrics', categoryId: '5', order: 4 },
    ],
    featured: false,
    order: 5,
    image: '/assets/fabrics/fabric1.jpeg',
  },
  {
    id: '6',
    name: 'Dupattas',
    slug: 'dupattas',
    subcategories: [
      { id: '6-1', name: 'Silk Dupattas', slug: 'silk-dupattas', categoryId: '6', order: 1 },
      { id: '6-2', name: 'Cotton Dupattas', slug: 'cotton-dupattas', categoryId: '6', order: 2 },
      { id: '6-3', name: 'Georgette Dupattas', slug: 'georgette-dupattas', categoryId: '6', order: 3 },
      { id: '6-4', name: 'Net Dupattas', slug: 'net-dupattas', categoryId: '6', order: 4 },
    ],
    featured: false,
    order: 6,
    image: '/assets/chiffon_dupatta/chiffon_dupatta1.jpeg',
  },
  {
    id: '7',
    name: 'Bedsheets',
    slug: 'bedsheets',
    subcategories: [
      { id: '7-1', name: 'Cotton Bedsheets', slug: 'cotton-bedsheets', categoryId: '7', order: 1 },
      { id: '7-2', name: 'Silk Bedsheets', slug: 'silk-bedsheets', categoryId: '7', order: 2 },
    ],
    featured: false,
    order: 7,
    image: '/assets/bedsheets/bedsheet1.jpeg',
  },
  {
    id: '8',
    name: 'Bags',
    slug: 'bags',
    subcategories: [
      { id: '8-1', name: 'Handbags', slug: 'handbags', categoryId: '8', order: 1 },
      { id: '8-2', name: 'Clutch Bags', slug: 'clutch-bags', categoryId: '8', order: 2 },
      { id: '8-3', name: 'Tote Bags', slug: 'tote-bags', categoryId: '8', order: 3 },
    ],
    featured: false,
    order: 8,
    image: '/assets/bags/bag1.jpeg',
  },
  {
    id: '9',
    name: "Men's Collection",
    slug: 'mens-collection',
    subcategories: [
      { id: '9-1', name: "Men's Kurtas", slug: 'mens-kurtas', categoryId: '9', order: 1 },
      { id: '9-2', name: "Men's Sherwanis", slug: 'mens-sherwanis', categoryId: '9', order: 2 },
      { id: '9-3', name: "Men's Accessories", slug: 'mens-accessories', categoryId: '9', order: 3 },
    ],
    featured: false,
    order: 9,
    image: '/assets/mens-collection/men-kurta1.jpeg',
  },
];

export const MOCK_PRODUCTS = [
  {
    id: '1',
    name: 'Elegant Silk Saree',
    description: 'Beautiful handwoven silk saree with intricate embroidery work',
    price: 2499,
    comparePrice: 3999,
    images: ['/assets/sarees/saree1.jpeg'],
    category: 'sarees',
    subcategory: 'silk-sarees',
    tags: ['silk', 'traditional', 'wedding'],
    stock: 15,
    sku: 'SS001',
    featured: true,
    status: 'active' as const,
    seoTitle: 'Elegant Silk Saree - Traditional Indian Wear',
    seoDescription: 'Shop our beautiful handwoven silk saree collection with intricate embroidery work',
    createdAt: new Date('2024-01-15T00:00:00.000Z'),
    updatedAt: new Date('2024-01-15T00:00:00.000Z'),
  },
  {
    id: '2',
    name: 'Designer Anarkali Suit',
    description: 'Stunning designer Anarkali suit perfect for special occasions',
    price: 3299,
    comparePrice: 4999,
    images: ['/assets/suit/suit1.jpeg'],
    category: 'suit-sets',
    subcategory: 'anarkali-suits',
    tags: ['designer', 'party-wear', 'anarkali'],
    stock: 8,
    sku: 'AS001',
    featured: true,
    status: 'active' as const,
    createdAt: new Date('2024-01-14T00:00:00.000Z'),
    updatedAt: new Date('2024-01-14T00:00:00.000Z'),
  },
  {
    id: '3',
    name: 'Cotton Dress Material',
    description: 'High-quality cotton dress material with beautiful prints',
    price: 899,
    comparePrice: 1299,
    images: ['/assets/dress-material/dress1.jpeg'],
    category: 'dress-material',
    tags: ['cotton', 'casual', 'comfortable'],
    stock: 25,
    sku: 'DM001',
    featured: false,
    status: 'active' as const,
    createdAt: new Date('2024-01-10T00:00:00.000Z'),
    updatedAt: new Date('2024-01-10T00:00:00.000Z'),
  },
  {
    id: '4',
    name: 'Classic Cotton Saree',
    description: 'Comfortable and elegant cotton saree for daily wear',
    price: 1299,
    comparePrice: 1899,
    images: ['/assets/sarees/saree2.jpeg'],
    category: 'sarees',
    subcategory: 'cotton-sarees',
    tags: ['cotton', 'casual', 'comfort'],
    stock: 20,
    sku: 'CS002',
    featured: false,
    status: 'active' as const,
    createdAt: new Date('2024-01-12T00:00:00.000Z'),
    updatedAt: new Date('2024-01-12T00:00:00.000Z'),
  },
  {
    id: '5',
    name: 'Georgette Palazzo Suit',
    description: 'Lightweight georgette palazzo suit with intricate detailing',
    price: 2799,
    comparePrice: 3599,
    images: ['/assets/suit/suit2.jpeg'],
    category: 'suit-sets',
    subcategory: 'palazzo-suits',
    tags: ['georgette', 'party-wear', 'palazzo'],
    stock: 10,
    sku: 'PS002',
    featured: true,
    status: 'active' as const,
    createdAt: new Date('2024-01-18T00:00:00.000Z'),
    updatedAt: new Date('2024-01-18T00:00:00.000Z'),
  },
  {
    id: '6',
    name: 'Chiffon Dupatta',
    description: 'Soft and flowy chiffon dupatta with elegant border',
    price: 499,
    comparePrice: 799,
    images: ['/assets/chiffon_dupatta/chiffon_dupatta1.jpeg'],
    category: 'dupattas',
    subcategory: 'chiffon-dupattas',
    tags: ['chiffon', 'dupatta', 'accessories'],
    stock: 30,
    sku: 'CD001',
    featured: false,
    status: 'active' as const,
    createdAt: new Date('2024-01-05T00:00:00.000Z'),
    updatedAt: new Date('2024-01-05T00:00:00.000Z'),
  },
  {
    id: '7',
    name: 'Silk Bedsheet Set',
    description: 'Luxurious silk bedsheet set with two pillow covers',
    price: 3999,
    comparePrice: 5999,
    images: ['/assets/bedsheets/bedsheet1.jpeg'],
    category: 'bedsheets',
    subcategory: 'silk-bedsheets',
    tags: ['silk', 'bedding', 'luxury'],
    stock: 7,
    sku: 'BS001',
    featured: true,
    status: 'active' as const,
    createdAt: new Date('2024-01-20T00:00:00.000Z'),
    updatedAt: new Date('2024-01-20T00:00:00.000Z'),
  },
  {
    id: '8',
    name: 'Embroidered Handbag',
    description: 'Stylish handbag with intricate embroidery, perfect for ethnic outfits',
    price: 1599,
    comparePrice: 2299,
    images: ['/assets/bags/bag1.jpeg'],
    category: 'bags',
    subcategory: 'handbags',
    tags: ['handbag', 'accessories', 'embroidered'],
    stock: 12,
    sku: 'HB001',
    featured: false,
    status: 'active' as const,
    createdAt: new Date('2024-01-22T00:00:00.000Z'),
    updatedAt: new Date('2024-01-22T00:00:00.000Z'),
  },
  {
    id: '9',
    name: "Men's Silk Kurta",
    description: 'Elegant silk kurta for men, ideal for festive occasions',
    price: 1999,
    comparePrice: 2899,
    images: ['/assets/mens-collection/men-kurta1.jpeg'],
    category: 'men\'s-collection',
    subcategory: 'men\'s-kurtas',
    tags: ['men', 'kurta', 'silk', 'festive'],
    stock: 18,
    sku: 'MK001',
    featured: true,
    status: 'active' as const,
    createdAt: new Date('2024-01-25T00:00:00.000Z'),
    updatedAt: new Date('2024-01-25T00:00:00.000Z'),
  },
  {
    id: '10',
    name: 'Home Decor Set',
    description: 'Elegant set of decorative items for your living room',
    price: 1200,
    images: ['/assets/home/decor1.jpeg'],
    category: 'home',
    tags: ['decor', 'home', 'living room'],
    stock: 20,
    sku: 'HD001',
    featured: false,
    status: 'active' as const,
    createdAt: new Date('2024-02-01T00:00:00.000Z'),
    updatedAt: new Date('2024-02-01T00:00:00.000Z'),
  },
  {
    id: '11',
    name: 'Handicraft Wall Art',
    description: 'Beautiful handmade wall art to enhance your home ambiance',
    price: 850,
    images: ['/assets/home/wallart1.jpeg'],
    category: 'home',
    tags: ['handicraft', 'wall art', 'home'],
    stock: 15,
    sku: 'HWA001',
    featured: false,
    status: 'active' as const,
    createdAt: new Date('2024-02-03T00:00:00.000Z'),
    updatedAt: new Date('2024-02-03T00:00:00.000Z'),
  },
  {
    id: '12',
    name: 'Comfortable Sofa Cushions',
    description: 'Soft and stylish cushions for your sofa, available in various colors',
    price: 300,
    images: ['/assets/home/cushion1.jpeg'],
    category: 'home',
    tags: ['cushions', 'sofa', 'home'],
    stock: 50,
    sku: 'CSC001',
    featured: false,
    status: 'active' as const,
    createdAt: new Date('2024-02-05T00:00:00.000Z'),
    updatedAt: new Date('2024-02-05T00:00:00.000Z'),
  },
  {
    id: '13',
    name: 'Premium Bath Towel Set',
    description: 'Luxurious and highly absorbent bath towel set',
    price: 950,
    images: ['/assets/home/towel1.jpeg'],
    category: 'home',
    tags: ['towel', 'bath', 'home'],
    stock: 30,
    sku: 'PBTS001',
    featured: true,
    status: 'active' as const,
    createdAt: new Date('2024-02-07T00:00:00.000Z'),
    updatedAt: new Date('2024-02-07T00:00:00.000Z'),
  },
];